# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f385e51dcec357165e9ab933f76492430515995c545e885ddb2c6f3c1d6c1b040fcc544c8670351838718301783cce590d68d7cab88497a330fc9473ddb3a28

test:
  secret_key_base: 619c1b233de830326300c9ae663c42d57a5c16b3c77ee2d4e2290c9d959318ff918a55d72d123cb3fa673a7f265b4161876f928684a6108e9b3623b40f02b406

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
